name: Deploy to Google Cloud VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami

    - name: Debugging
      run: |
        echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        echo "GCP_VM_USERNAME: ${{ secrets.GCP_VM_USERNAME }}"
        echo "GCP_VM_HOST: ${{ secrets.GCP_VM_HOST }}"

    - name: Deploy to Google Cloud VM
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.GCP_VM_HOST }}
        username: ${{ secrets.GCP_VM_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd mlproject/MLOPSPROJECT
          git pull origin main
          ls
